name: Check PR for specific file changes

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch for manual runs'
        required: true
        default: 'main'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Set target branch
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TARGET_BRANCH="${{ github.event.inputs.target_branch }}"
          else
            TARGET_BRANCH="main"
          fi
          echo "TARGET_BRANCH=$TARGET_BRANCH" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --all

      - name: Check for file changes
        run: |
          if [ "$TARGET_BRANCH" != "main" ]; then
            echo "TARGET_BRANCH=$TARGET_BRANCH"
            echo "Target branch is not main. Skipping file check."
            exit 0
          fi

          if ! git diff --name-only origin/main | grep -q "TextWrapper.cs"; then
            echo "TextWrapper.cs has not been changed. Rejecting PR."
            exit 1
          else
            echo "TextWrapper.cs has been changed. Proceeding with PR."
          fi